spin_manifest_version = 2

[application]
name = "mcp-web4"
version = "0.1.0"
authors = ["Multi Agency <multidaomensional@gmail.com>"]
description = "AI Proxy with MCP support"

[[trigger.http]]
route = "/..."
component = "mcp-web4"

[component.mcp-web4]
source = "mcp-web4/target/wasm32-wasip1/release/mcp_web4.wasm"
allowed_outbound_hosts = [
    "https://rpc.mainnet.fastnear.com:443",
    "https://api.openai.com:443",
    "https://*.openai.azure.com",
    "https://rpc.testnet.near.org:443",
    "https://rpc.mainnet.near.org:443",
    "http://localhost:14500",
    "http://127.0.0.1:3001",
    # Add any MCP server hosts you plan to connect to
    "https://*.mcp-server.com:443",
    "https://*:443", # HTTPS wildcard with port
    "http://*:80"    # HTTP wildcard with port
]
key_value_stores = ["default"]

[component.mcp-web4.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "mcp-web4"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
rpc_url = { required = true }
mcp_server_endpoint = { default = "https://9e54-107-13-130-95.ngrok-free.app" }

[component.mcp-web4.variables]
rpc_url = "{{ rpc_url }}"
mcp_server_endpoint = "{{ mcp_server_endpoint }}"